let a=30,b=30,c=30;
let d=a+b;
let e=a-b;
let f=a*b;
let g=b+c;
let h=b-c;
let i=b*c;
let j=c+a;
let k=c-a;
let l=c*a;
console.log("RESULTS :");
console.log("Sum of a and b => " +  d );
console.log("Subraction of a and b => " +  e);
console.log("Multiplication of a and b => " +  f);
console.log("Sum of a and b => " +  g);
console.log("Subraction of a and b => " +  h);
console.log("Multiplication of a and b => " +  i);
console.log("Sum of a and b => " +  j);
console.log("Subraction of a and b => " +  k);
console.log("Multiplication of a and b => " +  l);